### PR TITLE
corrects a time shift in the FlowNet schedule relative to data

### LINKED ISSUE #207: Date offset in observations compared to simulation results
Using  `time_ag_open_location`

image

### PR DESCRIPTION
**Pull request by olwijn**
*Insert a description of your pull request (PR) here, and check off the boxes below when they are done.*

---

### Contributor checklist

- [x] :tada: This PR closes #207.
- [x] :scroll: I have broken down my PR into the following tasks:
   - [ ] Create 2 data frames, one for generating the FlowNet schedule, and one for generating the observation set
   - [ ] Create to Schedule instances on the bases of these 2 dataframes
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`.
- [ ] :books: I have considered updating the documentation.

### CODE REVIEW

**Comment by wouterjdb** [comment]
CI/CD failing?

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.6/x64/bin/flownet", line 33, in <module>
    sys.exit(load_entry_point('flownet==0.1.dev1+g561b292', 'console_scripts', 'flownet')())
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/flownet/_command_line.py", line 274, in main
    args.func(args)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/flownet/_command_line.py", line 95, in flownet_pred
    run_flownet_prediction(config, args)
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/flownet/prediction/_run_pred.py", line 35, in run_flownet_prediction
    create_ert_setup(
  File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/flownet/ert/_create_ert_setup.py", line 210, in create_ert_setup
    if hasattr(config.ert, "analysis"):
AttributeError: 'list' object has no attribute 'ert'
```

**Comment by olwijn** [comment]
Not sure what is happening. On my VM, running Python 3.6:
image

**Comment by olelod** [comment]
I wonder if we will not get the same result by simply moving

```
{%- if date > startdate: %}
DATES
 {{ date.strftime('%d %b %Y').upper() }} /
/
{%- endif %}
```

in the template file HISTORY_SCHEDULE.inc.jinja2 to the end of the for loop instead of the beginning.

https://github.com/equinor/flownet/blob/master/src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2#L2 to https://github.com/equinor/flownet/blob/master/src/flownet/templates/HISTORY_SCHEDULE.inc.jinja2#L47

This will also move the WELSPECS and COMPDAT keywords, but new wells seems to always be introduced with 'STOP' in WCONHIST (which are removed in your PR, right?).

**Comment by olwijn** [comment]
@olelod A quick test suggests that you are right, this is a much smarter solution.

**Review by olelod — APPROVED** [review]
LGTM

**Pull request merged**
