### PR TITLE
Fixes usage of lists in yaml analysis config

### LINKED ISSUE #241: Incorrect usage of lists in yaml in the analytics configuration
Incorrect usage of list in in YAML file for analysis configiration:

```
  analysis:
    metric: "[RMSE,MAE]"
    quantity: "[WOPR:PROD,WWPR:PROD]"
    start: "2011-01-01"
    end: "2016-06-01"
    outfile: analysis_metrics_iteration
```

### PR DESCRIPTION
**Pull request by edubarrosTNO**
Fixes usage of lists in analysis part of FlowNet YAML configuration file: prescribing a proper list instead of a string

---

### Contributor checklist

- [ ] :tada: This PR closes #241 
- [ ] :scroll: I have broken down my PR into the following tasks:
   - [ ] Changes in the config_parser
   - [ ] Changes in create_ert_setup to render list in ERT config file
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`.
- [ ] :books: I have considered updating the documentation.

### CODE REVIEW

**Review by wouterjdb — CHANGES_REQUESTED** [review]
Looks good. Could you run a quick test with your test-data branch? If it passes CI it is a 👍

**Comment by edubarrosTNO** [comment]
I think we might have to merge https://github.com/equinor/flownet-testdata/pull/28 before this one can pass the CI here

**Comment by wouterjdb** [comment]
> I think we might have to merge [equinor/flownet-testdata#28](https://github.com/equinor/flownet-testdata/pull/28) before this one can pass the CI here

No, you can change the github workflow [file](https://github.com/equinor/flownet/blob/master/.github/workflows/flownet.yml) to temporarily use your fork/brnach of the testdata repo to perform the test before merging.

**Review by wouterjdb — APPROVED** [review]
LGTM 👍

**Pull request merged**
