### PR TITLE
Add about page

### LINKED ISSUE #126: Create "About FlowNet page" in documentation with logos
In a  review for #115 (@tayloris) it was suggested to make an about page with logos. This issue is to make sure that is followed up.

### PR DESCRIPTION
**Pull request by wouterjdb**
Closes #126 

Looks like:
image

I'd like to have a specific approval for this PR (usage of logos) from both TNO and SINTEF before merging.

@edubarrosTNO @olwijn @tayloris

### CODE REVIEW

**Review by tayloris — APPROVED** [review]
Excellent, it looks nice.     If you agree, I suggest to include a link if a person clicks the Sintef logo to be redirected to  our group page  
 <https://www.sintef.no/en/digital/applied-mathematics/computational-geoscience/>  
 Anyhow,   I'll approve the use of the logo with or without the suggestion of the link to the picture.  Many thanks

**Comment by anders-kiaer** [comment]
Do we have SVG logos available for TNO and SINTEF as well?

**Comment by wouterjdb** [comment]
> Do we have SVG logos available for TNO and SINTEF as well?

I searched for those but after wasting some time on it I gave up. For SINTEF the eps-logo is easily obtained. I tried to use that but Inkscape crashed 🥳 . Anyways, I gave up on it. 🐔

**Comment by tayloris** [comment]
I have access to Sintef logo in .png and .eps format. Also, I can export the logo as .svg  by importing the eps logo in insckape.

**Comment by wouterjdb** [comment]
> I have access to Sintef logo in .png and .eps format. Also, I can export the logo as .svg by importing the eps logo in insckape.

If you could give that a try we can include the nice svg format.

**Review by edubarrosTNO — APPROVED** [review]
👍

**Pull request merged**
