### PR TITLE
Add Python 3.9 Support

### PR DESCRIPTION
**Pull request by wouterjdb**
This PR tests the usage of Python 3.9

---

### Contributor checklist

- [ ] :tada: This PR closes #ISSUE_NUMBER.
- [ ] :scroll: I have broken down my PR into the following tasks:
   - [ ] Task 1
   - [ ] Task 2
- [ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.
- [ ] :book: I have considered adding a new entry in `CHANGELOG.md`.
- [ ] :books: I have considered updating the documentation.

### CODE REVIEW

**Comment by wouterjdb** [comment]
```
ERROR: Could not find a version that satisfies the requirement ecl>=2.9 (from flownet)
ERROR: No matching distribution found for ecl>=2.9
Error: Process completed with exit code 1.
```

**Comment by wouterjdb** [comment]
`ecl 2.10.1` now exists with py39 support

**Comment by wouterjdb** [comment]
`equinor-libres` doesn't have Python 3.9 support yet.

**Comment by wouterjdb** [comment]
https://pypi.org/project/equinor-libres/9.0.1/ now supports Python 3.9.

**Comment by wouterjdb** [comment]
`pyvista`, or actually its dependecy `vtk` is not yet supported on Python 3.9.

**Comment by wouterjdb** [comment]
Pyvista should now support Python3.9: https://github.com/pyvista/pyvista/releases/tag/0.31.3

**Comment by wouterjdb** [comment]
The new pip dependency resolver results in very slow installation performance. A quick solution for this could be to use the legacy dependency resolver, like so: `--use-deprecated=legacy-resolver`

**Comment by wouterjdb** [comment]
XTgeo doesn't support 3.9 yet - but the pre-releases do.... Shouldn't take too long: https://github.com/equinor/xtgeo/releases

**Review by fahaddilib — APPROVED** [review]
Thanks for the update!

**Pull request merged**
